# Generated by Django 4.1.4 on 2023-01-04 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdncode', models.CharField(default=uuid.uuid1, max_length=8)),
            ],
        ),
    ]
